using System;
using System.Xml;
using System.Xml.Schema;
using System.Xml.Serialization;

namespace iCloud.Dav.Auth.CardDav.Types
{
    /// <summary>
    /// Represents a WebDAV propfind request to retrieve properties for a resource.
    /// </summary>
    [XmlRoot(ElementName = "propfind", Namespace = "DAV:")]
    internal sealed class PropFind : IXmlSerializable
    {
        /// <summary>
        /// Gets or sets a value indicating whether to include the addressbook home set in the response.
        /// </summary>
        public bool AddressBookHomeSet { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether to include the current user principal in the response.
        /// </summary>
        public bool CurrentUserPrincipal { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether to include the display name in the response.
        /// </summary>
        public bool DisplayName { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether to include the calendar home set in the response.
        /// </summary>
        public bool CalendarHomeSet { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether to include the calendar user address set in the response.
        /// </summary>
        public bool CalendarUserAddressSet { get; set; }

        /// <summary>
        /// Returns the XML schema for this instance.
        /// </summary>
        /// <returns>An <see cref="XmlSchema"/> object that describes the XML representation of the object that is generated by the <see cref="WriteXml(XmlWriter)"/> method and consumed by the <see cref="ReadXml(XmlReader)"/> method.</returns>
        public XmlSchema GetSchema() => new XmlSchema();

        /// <summary>
        /// This method is not supported.
        /// </summary>
        /// <param name="reader">Not used.</param>
        public void ReadXml(XmlReader reader) => throw new NotSupportedException();

        /// <summary>
        /// Generates the XML representation of this instance.
        /// </summary>
        /// <param name="writer">The <see cref="XmlWriter"/> to which to write the XML.</param>
        public void WriteXml(XmlWriter writer)
        {
            writer.WriteStartElement("prop", "DAV:");

            if (AddressBookHomeSet)
            {
                writer.WriteElementString("addressbook-home-set", "urn:ietf:params:xml:ns:caldav", null);
            }

            if (CurrentUserPrincipal)
            {
                writer.WriteElementString("current-user-principal", "DAV:", null);
            }

            if (DisplayName)
            {
                writer.WriteElementString("displayname", "DAV:", null);
            }

            if (CalendarHomeSet)
            {
                writer.WriteElementString("calendar-home-set", "urn:ietf:params:xml:ns:caldav", null);
            }

            if (CalendarUserAddressSet)
            {
                writer.WriteElementString("calendar-user-address-set", "urn:ietf:params:xml:ns:caldav", null);
            }

            writer.WriteFullEndElement();
        }
    }
}